### ISSUE TITLE
preview partly hidden

### ISSUE THREAD

**Issue by marcmo** [esrlabs/logviewer#141]
v0.8.0
![image](https://user-images.githubusercontent.com/99541/36672633-52be4fea-1b00-11e8-9042-54267464188e.png)
![image](https://user-images.githubusercontent.com/99541/36672642-594f7bf4-1b00-11e8-82d5-756e445c16ee.png)

**Comment by DmitryAstafyev** [comment]
I think it can be closed, because as far as I can see it isn't reproduced on: mac, win and linux
