### ISSUE TITLE
Slow work

### ISSUE THREAD

**Issue by DmitryAstafyev** [esrlabs/logviewer#176]
# Prerequisites

affected version:

make sure to check this before filing an issue:

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

# Expected Behavior
Logviewer should work as well

# Current Behavior
With telnet connection. 
After ~12000 lines of logs, logviewer starts to work very-very slow. Indicator of searching process (right-bottom corner) always shows some work is going. In ~30 seconds work became to normal. 

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

## Context

* Operating System: win
* node version: desktop
* npm version: desktop

## Failure Logs

Please include any relevant log snippets or files here.

**Comment by marcmo** [comment]
solved for v2
