### ISSUE TITLE
Setting of State monitor view

### ISSUE THREAD

**Issue by DmitryAstafyev** [esrlabs/logviewer#198]
# Prerequisites

affected version: 0.16.2

make sure to check this before filing an issue:

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

# Expected Behavior
State monitor settings can be used.

# Current Behavior
- Currently icons not visible for a dark theme.
- Time to time impossible to remove items in the settings tab

## Steps to Reproduce

Try to change/create state monitor configuration

## Context

* Operating System: all
* node version:
* npm version:

**Comment by marcmo** [comment]
old issue...will be included in event plugin
