### ISSUE TITLE
jump to next/previous match needs to be next to the search bar

### ISSUE THREAD

**Issue by marcmo** [esrlabs/logviewer#220]
the next/prev match arrows
![image](https://user-images.githubusercontent.com/99541/42305054-7f80215a-8029-11e8-9696-6ccd302dbd25.png)
should be in here
![image](https://user-images.githubusercontent.com/99541/42305066-8e9b934a-8029-11e8-9283-1f630391fec0.png)

**Comment by DmitryAstafyev** [comment]
fixed with 0.24.9
