### ISSUE TITLE
the location in file bar needs get better visibility

### ISSUE THREAD

**Issue by marcmo** [esrlabs/logviewer#222]
![image](https://user-images.githubusercontent.com/99541/42305281-823db866-802a-11e8-84b2-78fc42b7c264.png)
should at least have a bright color

**Comment by DmitryAstafyev** [comment]
The white corner between scrollbars is corrected from 0.22.0

**Comment by DmitryAstafyev** [comment]
A selected line in the main view (and search results view) is marked in numbers area. Extra highlight selected line in the main view can be in conflict with highlighting of search results and markers. So think the best place for highlighting of current selection is only numbers-area
