### ISSUE TITLE
Grouping of filters

### ISSUE THREAD

**Issue by elektronenhirn** [esrlabs/logviewer#238]
I am creating more and more filters (aka requests). Usually I need not just one active filter for analyses, but rather multiple ones. For example I have 4 filters I need for hunting power management related bugs.

I would be great to have a possibility to group filters and activate/deactivate them all at once.

**Comment by DmitryAstafyev** [comment]
Grouping of filter already implemented. 
![screenshot 2018-11-13 at 09 10 17](https://user-images.githubusercontent.com/12843747/48399566-48bd3b00-e724-11e8-8756-4ae7888481b6.png)
You are able:
- create/save presets (groups)
- export/import presets (groups)
