### ISSUE TITLE
Logviewer creates directory logviewer on Desktop

### ISSUE THREAD

**Issue by flxo** [esrlabs/logviewer#246]
# Prerequisites

affected version:

make sure to check this before filing an issue:

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

# Expected Behavior

No files or directories created on desktop. Use `~/.cache/logviewer` on Linux and ~/Library/Application Support/...` on mac. Don't know whats the place to use on Windows.

# Current Behavior

After startup logviewer stores something on desktop.

## Steps to Reproduce

Start logviewer

## Context

* Operating System: macos

**Comment by marcmo** [comment]
resolved
