### ISSUE TITLE
add support to render columns in DLT

### ISSUE THREAD

**Issue by marcmo** [esrlabs/logviewer#273]
dlt content should be easy to visually scan. coloring different sections an arranging them in columns should be sufficient to improve this
see [rogcat](https://github.com/flxo/rogcat) as an example
![image](https://user-images.githubusercontent.com/99541/59049901-4c174000-8889-11e9-9315-c36ad6c96791.png)

**Comment by DmitryAstafyev** [comment]
solved 1.8.0
