### ISSUE TITLE
Merge tool (logviewer_indexer): stderr

### ISSUE THREAD

**Issue by DmitryAstafyev** [esrlabs/logviewer#283]
# Prerequisites

affected version:0.19.0

make sure to check this before filing an issue:

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

# Expected Behavior
`stderr` used only for posting errors (which should stop process and reject it)

# Current Behavior
`stderr` has some environment / debug messages, like:
```
parsing: [32, 30, 33, 37, 37, 31, 30, 32, 02, 0A] => last row_nr: 20377102
```
## Steps to Reproduce

Merge any few files. Posting to stderr happens at the end of operation

**Comment by marcmo** [comment]
fixed with in 0.20.0
