### ISSUE TITLE
plugin area becomes unresponsive

### ISSUE THREAD

**Issue by marcmo** [esrlabs/logviewer#287]
# Prerequisites

affected version:
1.7.2

# Expected Behavior

# Current Behavior

plugin tabs cannot be selected anymore

## Steps to Reproduce

* open second tab
* switch sides of plugin area

## Context

* Operating System: mac os
* node version:
* npm version:

## Failure Logs

Please include any relevant log snippets or files here.

**Comment by DmitryAstafyev** [comment]
fixed with 1.7.3
