### ISSUE TITLE
[logviewer_indexing] format subcommand doesn't return result 

### ISSUE THREAD

**Issue by DmitryAstafyev** [esrlabs/logviewer#290]
# Prerequisites

affected version: 0.21.1

make sure to check this before filing an issue:

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

# Expected Behavior
get in stdout output like
```
{
  "regex":"(?P<m>\\d{2})-(?P<d>\\d{2})-(?P<Y>\\d{4})\\s+(?P<H>\\d{2}):(?P<M>\\d{2}):(?P<S>\\d{2})\\.(?P<millis>\\d+)",
  "matching_lines":10,
  "nonmatching_lines":2,
  "processed_bytes":320
}
```

# Current Behavior
* nothing in stdout;
* nothing in stderr;

## Steps to Reproduce

command
```
lvin format -c ./1561796868639-652-694-119.json
```

config file
```
{"file":"./timestamp_a.log","format":"MM-DD-YYYY hh:mm:ss.s","lines_to_test":1000}
```
#289

**Comment by marcmo** [comment]
fixed with logviewer_indexer 0.21.2
