### ISSUE TITLE
[logviewer_indexer] stderr message

### ISSUE THREAD

**Issue by DmitryAstafyev** [esrlabs/logviewer#291]
# Prerequisites

affected version: 0.21.3

make sure to check this before filing an issue:

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

# Expected Behavior
no any messages in stderr, except errors

# Current Behavior
if output file is empty, stderr has message:
```
file was empty => next_line_nr was 0
```

command:
```
lvin merge ./1561968577893-727-489-327.json -s -a -o ./small.log.indexed
```

file `small.log.indexed` is empty (size of file is 0 bytes)

**Comment by marcmo** [comment]
fixed with 0.21.4
