### ISSUE TITLE
"Plus" sign in bottom section doesn't open new search

### ISSUE THREAD

**Issue by davide-esr** [esrlabs/logviewer#300]
# Prerequisites

affected version: 1.7.5

make sure to check this before filing an issue:

- [x] I am running the latest version
- [x] I checked the documentation and found no ~~answer~~ documentation
- [x] I checked to make sure that this issue has not already been filed

# Expected Behavior
When hitting the plus sign, a search tab shows up

# Current Behavior
I mistakenly closed the search tab, tried to open a new one. The Plus sign just collapses the bottom section

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce

Click on the "plus" sign in the bottom section

## Context

* Operating System: MacOS 10.14.4
* node version: v11.6.0
* npm version: 6.5.0-next.0

## Failure Logs
N/A

Please include any relevant log snippets or files here.
N/A

**Comment by DmitryAstafyev** [comment]
solved 1.8.0
