### ISSUE TITLE
Remote installation service

### ISSUE THREAD

**Issue by DmitryAstafyev** [esrlabs/logviewer#35]
Developer should have possibility to install logviewer-service remotely. Workflow can looks like next:
* viewer: user define IP address, login and password of destination machine
* service: using ssh, service connects to destination machine and install service there
* service: detect IP of installed logviewer's service and send it to viewer
* viewer: automatically switched to just installed service
* [optional] viewer shows selection of serial ports

**Comment by marcmo** [comment]
not applicable for v2 anymore
