### ISSUE TITLE
copy does not work reliably 

### ISSUE THREAD

**Issue by marcmo** [esrlabs/logviewer#375]
# Prerequisites

affected version: 1.16.1

make sure to check this before filing an issue:

- [ ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

# Expected Behavior

selection will be put to clipboard with Cmd+C or with copy context menu
![image](https://user-images.githubusercontent.com/99541/62113202-73e8ba00-b2b4-11e9-9b7a-eecdc8a4a6ee.png)

# Current Behavior

nothing is put to clipboard

**Comment by DmitryAstafyev** [comment]
fixed with 1.16.2
